config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update', as: :task_update
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(tasks_strong_params)
    task.save
    redirect_to tasks_path
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(tasks_strong_params)
    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def tasks_strong_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.label :completed %>
  <%= t.check_box :completed %>

  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit your task</h1>
<h2><%= @task.title %></h2>
<br>
<%= render 'form', task: @task%>
<br>
<%= link_to 'Go back to the list', tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks :</h1>
<% @tasks.each do |task| %>
<% if task.completed == true %>
  <input type="checkbox" checked>
<% else %>
  <input type="checkbox">
<% end %>
<%= link_to task.title, task_path(task) %>
<%= link_to "🗑", task_path(task), method: :delete, data: {confirm: 'are you sure?'} %>
<br>
<br>
<% end %>
<%= link_to 'Add a new task', new_task_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task%>
<br>
<%= link_to 'Go back to the list', tasks_path %>

app/views/tasks/show.html.erb
<h1>Here are the details</h1>
<h2><%= @task.title %></h2>
<%= @task.details %>
<br>
<% if @task.completed == false %>
  <input type="checkbox" >
<p>This task is not completed yet!</p>
<% else %>
  <input type="checkbox" checked>
  <p>This task is done ! :) </p>
<% end %>
<%= link_to 'Edit your task', task_edit_path %>
<br>
<%= link_to 'Go back to the list', tasks_path %>